name: Update Publications

on:
  # Run monthly on the 1st at 9am UTC
  schedule:
    - cron: '0 9 1 * *'

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      year:
        description: 'Year to fetch publications for'
        required: false
        default: ''

jobs:
  update-publications:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests pyyaml

    - name: Fetch publications
      env:
        SEMANTIC_SCHOLAR_ID: ${{ secrets.SEMANTIC_SCHOLAR_AUTHOR_ID }}
      run: |
        YEAR=${{ github.event.inputs.year }}
        if [ -z "$YEAR" ]; then
          YEAR=$(date +%Y)
        fi

        echo "Fetching publications for year: $YEAR"
        python automation/update_publications.py \
          --year $YEAR \
          --author-id $SEMANTIC_SCHOLAR_ID \
          --output _data/publications_candidate.yml

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update publications via automation'
        title: '[Automated] New Publications Found'
        body: |
          This PR was automatically generated by the publications update workflow.

          ## Changes
          New publications have been fetched and formatted. Please review:
          - Check publication details for accuracy
          - Add missing descriptions or abstracts
          - Add PDF links or thumbnails if available
          - Verify journal/conference names

          Once reviewed, you can merge this PR to update the website.

          ---
          Generated by GitHub Actions workflow
        branch: automated-publications-update
        delete-branch: true
        labels: automated, publications
